spring:
  application:
    name: examen
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
jwt:
  private-key-path: keys/private_key.pem
  public-key-path: keys/public_key.pem
